[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd client && npm ci"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd client && npx serve -s build -l $PORT"
